# Generated by Django 3.1.4 on 2021-07-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
