# Generated by Django 3.1.4 on 2021-07-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0002_auto_20210706_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('Technology', 'Technology'), ('Law', 'Law'), ('Art', 'Art'), ('Business', 'Business'), ('Health', 'Health')], default='Other', max_length=20)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.student')),
            ],
        ),
    ]
