# Generated by Django 3.1.4 on 2021-07-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0003_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000),
        ),
    ]
