# Generated by Django 3.1.4 on 2021-07-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0006_auto_20210707_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('points', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(max_length=1000)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.assignment')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(default=1)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.course'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classmanager.course')),
            ],
        ),
    ]
