# Generated by Django 3.1.4 on 2021-07-11 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0008_auto_20210710_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=datetime.date(2021, 7, 14)),
        ),
    ]
