# Generated by Django 3.1.4 on 2021-07-11 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0009_auto_20210711_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
