# Generated by Django 3.1.4 on 2021-07-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classmanager', '0010_submission_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmanager.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmanager.student')),
            ],
        ),
    ]
